# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ON', 'on'), ('OFF', 'of')], default='ON', max_length=5)),
            ],
        ),
    ]
