# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160115_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dispositivo',
            new_name='Receptor',
        ),
    ]
